#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

python manage.py migrate
python manage.py collectstatic --noinput

exec gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
