# Generated by Django 5.1.11 on 2026-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_tg_hash_id'),
        ('category', '0002_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories_busines_11ea6f_idx',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'name_uz'], name='categories_busines_25d53a_idx'),
        ),
    ]
