# Generated by Django 5.1.7 on 2025-04-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FREE', 'Free'), ('FIXED', 'Fixed Price'), ('FLEXIBLE', 'Flexible Price')], max_length=15)),
                ('max_km', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.JSONField(blank=True, null=True)),
                ('cities', models.JSONField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_km', models.PositiveIntegerField(blank=True, null=True)),
                ('initial_km_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('every_km_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_shipping_time', models.DurationField(blank=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='business.branch')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_methods', to='business.business')),
            ],
            options={
                'verbose_name': 'Delivery Method',
                'verbose_name_plural': 'Delivery Methods',
            },
        ),
        migrations.CreateModel(
            name='PickupMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branches', models.ManyToManyField(blank=True, to='business.branch')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_methods', to='business.business')),
            ],
        ),
    ]
