# Generated by Django 5.1.11 on 2025-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethod',
            name='estimated_shipping_time',
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='every_km_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='initial_km_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
