# Generated by Django 5.1.11 on 2025-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliverymethod_estimated_shipping_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='estimated_shipping_time',
            field=models.PositiveIntegerField(blank=True, help_text='Yetkazib berish vaqti (soatda)', null=True),
        ),
    ]
