# Generated by Django 5.1.7 on 2025-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='desktop_image',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
