# Generated by Django 5.1.11 on 2025-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='favicon',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='platform_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('telegram_bot_web', 'Telegram Bot and Web')], default='telegram_bot_web', max_length=20),
        ),
    ]
