# Generated by Django 5.1.11 on 2025-08-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_favicon_alter_subscription_platform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_stats', to='business.business')),
            ],
            options={
                'unique_together': {('business', 'platform', 'date')},
            },
        ),
    ]
