# Generated by Django 5.1.11 on 2025-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_trafficstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tg_hash_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
