# Generated by Django 5.1.11 on 2026-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_tr',
            field=models.TextField(blank=True),
        ),
    ]
