# Generated by Django 5.1.11 on 2025-07-24 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='last_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('activation', 'Account Activation'), ('password_reset', 'Password Reset')], default='activation', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('user', 'type')},
        ),
    ]
