# Generated by Django 5.1.11 on 2025-08-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_otp_options_remove_user_is_email_verified_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('store', 'Store')], default='dashboard', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', None), _negated=True), fields=('business_id', 'phone_number'), name='unique_phone_number_per_business'),
        ),
    ]
