# Generated by Django 5.1.11 on 2025-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_remove_user_unique_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('store', 'Store'), ('mobile', 'Mobile')], default='dashboard', max_length=20),
        ),
    ]
